# Generated by Django 6.0 on 2026-01-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='livros/'),
        ),
    ]
